import nodemailer from "nodemailer";

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { to, ticker, signal, analysis } = req.body;

  if (!to || !ticker || !signal || !analysis) {
    return res.status(400).json({ error: "Missing required fields" });
  }

  // Basic email validation
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(to)) {
    return res.status(400).json({ error: "Invalid email address" });
  }

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS, // Gmail App Password (not your real password)
    },
  });

  const signalColor = signal === "BUY" ? "#00ff9d" : signal === "SELL" ? "#ff6b35" : "#00d4ff";
  const signalEmoji = signal === "BUY" ? "📈" : signal === "SELL" ? "📉" : "⏸";

  const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Market Alert: ${ticker}</title>
</head>
<body style="margin:0;padding:0;background:#060a0f;font-family:'Helvetica Neue',Arial,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:32px 20px;">

    <!-- Header -->
    <div style="text-align:center;margin-bottom:32px;">
      <div style="width:1px;height:40px;background:linear-gradient(to bottom,transparent,#00d4ff);margin:0 auto 16px;"></div>
      <div style="font-size:11px;letter-spacing:3px;color:#00d4ff;text-transform:uppercase;margin-bottom:8px;">Market Intelligence Alert</div>
      <h1 style="font-size:28px;font-weight:800;color:#ffffff;margin:0;letter-spacing:-0.5px;">Trade Signal Detected</h1>
    </div>

    <!-- Signal Card -->
    <div style="background:#0f1e2e;border:1px solid #1a2a3a;border-radius:16px;padding:28px;margin-bottom:20px;position:relative;overflow:hidden;">
      <div style="height:3px;background:linear-gradient(90deg,#00d4ff,#00ff9d);margin:-28px -28px 24px;border-radius:16px 16px 0 0;"></div>

      <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:20px;flex-wrap:wrap;gap:12px;">
        <div>
          <div style="font-size:11px;letter-spacing:2px;color:#4a6a7a;text-transform:uppercase;margin-bottom:6px;">Ticker</div>
          <div style="font-size:32px;font-weight:700;color:#ffffff;letter-spacing:3px;font-family:monospace;">${ticker}</div>
        </div>
        <div style="text-align:right;">
          <div style="font-size:11px;letter-spacing:2px;color:#4a6a7a;text-transform:uppercase;margin-bottom:6px;">Signal</div>
          <div style="font-size:28px;font-weight:800;color:${signalColor};letter-spacing:2px;">${signalEmoji} ${signal}</div>
        </div>
      </div>

      <div style="background:#060a0f;border-radius:10px;padding:20px;border-left:3px solid ${signalColor};">
        <div style="font-size:11px;letter-spacing:2px;color:#4a6a7a;text-transform:uppercase;margin-bottom:10px;">Analysis Summary</div>
        <div style="font-size:14px;color:#b0c8d4;line-height:1.8;white-space:pre-wrap;">${analysis.substring(0, 1200)}${analysis.length > 1200 ? "..." : ""}</div>
      </div>
    </div>

    <!-- Timestamp -->
    <div style="text-align:center;margin-bottom:20px;">
      <span style="font-size:11px;color:#4a6a7a;font-family:monospace;letter-spacing:1px;">
        Generated: ${new Date().toUTCString()}
      </span>
    </div>

    <!-- Disclaimer -->
    <div style="background:rgba(255,107,53,0.05);border:1px solid rgba(255,107,53,0.15);border-radius:10px;padding:16px;">
      <p style="font-size:11px;color:#6a7a8a;line-height:1.6;margin:0;font-family:monospace;">
        <strong style="color:#ff6b35;">⚠ DISCLAIMER:</strong> This alert is generated by AI for educational purposes only.
        It does not constitute financial advice. Always consult a licensed financial advisor before making
        investment decisions. Past performance does not guarantee future results.
      </p>
    </div>

    <!-- Footer -->
    <div style="text-align:center;margin-top:24px;">
      <p style="font-size:11px;color:#2a3a4a;letter-spacing:1px;font-family:monospace;">
        MARKET INTELLIGENCE · POWERED BY CLAUDE AI
      </p>
    </div>

  </div>
</body>
</html>
  `;

  try {
    await transporter.sendMail({
      from: `"Market Intelligence" <${process.env.EMAIL_USER}>`,
      to,
      subject: `${signalEmoji} ${signal} Signal: ${ticker} — Market Intelligence Alert`,
      html: htmlBody,
      text: `Market Intelligence Alert\n\n${ticker} — ${signal}\n\n${analysis}\n\nDISCLAIMER: Educational purposes only. Not financial advice.`,
    });

    return res.status(200).json({ success: true });
  } catch (err) {
    console.error("Email error:", err);
    return res.status(500).json({ error: "Failed to send email. Check your email credentials." });
  }
}
